//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsharpV1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZHOUYIEntities : DbContext
    {
        public ZHOUYIEntities()
            : base("name=ZHOUYIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Notation> Notation { get; set; }
    }
}
