//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsharpV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Firstname { get; set; }
        public string Promotion_during_validation { get; set; }
        public string Current_Promotion { get; set; }
        public string E_mail { get; set; }
        public string Campus { get; set; }
        public string Courses_would_teach { get; set; }
        public string Courses_already_teach { get; set; }
        public string Campus_already_in { get; set; }
        public string Campus_would_in { get; set; }
        public string Certifications { get; set; }
        public string comments { get; set; }
    }
}
